name: churn-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas>=2.0
  - scikit-learn>=1.3
  - mysql-connector-python>=8.0
  - python-dotenv>=1.0
  - pip
  - pip:
      # optional pip-only deps (if you ever add them)
      # - some-pip-only-package
