name: CI

on: [push, pull_request]

jobs:
  sanity-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt || echo "No requirements yet"

      - name: Lint
        run: flake8 src/ sql/ || echo "No linting yet"

      - name: Run tests (placeholder)
        run: pytest || echo "No tests yet"